---
colors:
  up: "#00c853"
  empty: "#708090"

cellColorMappings:
  darkTheme:
    up: up
    empty: empty

thresholds:
  operstatus:
    - { color: up, level: 1 }   # up
    - { color: empty, level: 2 }   # empty